"""add storage medium

Revision ID: 43e48e662978
Revises: 8d763c7280de
Create Date: 2023-05-20 03:08:54.638752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e48e662978'
down_revision = '8d763c7280de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webmon_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webmon_user', schema=None) as batch_op:
        batch_op.drop_column('storage')

    # ### end Alembic commands ###
