"""add reporter metadata

Revision ID: 8d763c7280de
Revises: e564d9343ec3
Create Date: 2023-05-20 01:11:27.173854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d763c7280de'
down_revision = 'e564d9343ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webmon_reporter',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['webmon_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webmon_reporter')
    # ### end Alembic commands ###
