"""add storage medium

Revision ID: cf97f730a036
Revises: 43e48e662978
Create Date: 2023-05-20 03:09:43.585177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf97f730a036'
down_revision = '43e48e662978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webmon_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_medium', sa.String(length=200), nullable=False))
        batch_op.drop_column('storage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webmon_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('storage_medium')

    # ### end Alembic commands ###
