SECRET_KEY = "caa6b5753f34b21c25d66ec68b55d252dc3fcd77c0cff15201df124d591d0b6e"
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_FOLDER = "./storage"
MAX_CONTENT_LENGTH = 109951162777600

# database config mysql
# SQLALCHEMY_DATABASE_URI = "mysql+pymysql://(user):(password)@(hosy)/(database)"
#SQLALCHEMY_DATABASE_URI = "mysql+pymysql://remote:Kunciku%40@103.150.256.69/webmon_test"

# database config mariadb
SQLALCHEMY_DATABASE_URI = "mariadb+mariadbconnector://remote:Kunciku2323@103.150.253.69/webmon_test"

ALLOWED_EXTENSIONS = ["slg"]
