SECRET_KEY = "c5a5b02706891259dcd0332ea092a8b8d6fbd7df97a73240a5bfe41a0be6c751"
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_FOLDER = "./storage"
MAX_CONTENT_LENGTH = 109951162777600
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://admin:admin123@localhost/webmon"
ALLOWED_EXTENSIONS = [ "slg" ]